/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import crud.UsuarioCRUD;
import domain.Usuario;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael S. Guimarães <rafaelg@ifes.edu.br>
 */
public class FrmListaUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form FrmListaUsuarios
     */
    FrmUsuario frmUsuario = new FrmUsuario();
    
    public FrmListaUsuarios() {
        initComponents();
        frmUsuario.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    public void addRowsToTable(){
        DefaultTableModel modelo = (DefaultTableModel) jtListaUsuarios.getModel();
        
        modelo.getDataVector().removeAllElements();
        
        Connection conn = database.DatabaseFactory
                .getDatabase("postgresql").connect();
        
        UsuarioCRUD usuarioCrud = new UsuarioCRUD();
        
        Object rowData[] = new Object[5];
        
        if(tfFiltro.getText().equals("")){
            for(Usuario aux: usuarioCrud.read(conn)){
                rowData[0] = aux.getId();
                rowData[1] = aux.getNome();
                rowData[2] = aux.getSenha();
                rowData[3] = aux.getDescricao();
                rowData[4] = aux.getPerfil();

                modelo.addRow(rowData);
            }
        }else{
            for(Usuario aux: usuarioCrud.read(conn, tfFiltro.getText())){
                rowData[0] = aux.getId();
                rowData[1] = aux.getNome();
                rowData[2] = aux.getSenha();
                rowData[3] = aux.getDescricao();
                rowData[4] = aux.getPerfil();

                modelo.addRow(rowData);
            }
        }
        
        database.DatabaseFactory.getDatabase("postgresql").disconnect(conn);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfFiltro = new javax.swing.JTextField();
        btListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btListar.setText("Listar");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });

        jtListaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "SENHA", "DESCRIÇÃO", "PERFIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtListaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListaUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btListar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btListar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed
        addRowsToTable();
    }//GEN-LAST:event_btListarActionPerformed

    private void jtListaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListaUsuariosMouseClicked
        int index = jtListaUsuarios.getSelectedRow();
        
        DefaultTableModel modelo = (DefaultTableModel) jtListaUsuarios.getModel();
        
        Usuario aux = new Usuario();
        
        aux.setId(Integer.parseInt(modelo.getValueAt(index, 0).toString()));
        aux.setNome(modelo.getValueAt(index, 1).toString());
        aux.setSenha(modelo.getValueAt(index, 2).toString());
        aux.setDescricao(modelo.getValueAt(index, 3).toString());
        aux.setPerfil(Integer.parseInt(modelo.getValueAt(index, 4).toString()));
        
        frmUsuario.tfId.setText(String.valueOf(aux.getId()));
        frmUsuario.tfNome.setText(aux.getNome());
        frmUsuario.tfSenha.setText(aux.getSenha());
        frmUsuario.tfDescricao.setText(aux.getDescricao());
        frmUsuario.tfPerfil.setText(String.valueOf(aux.getPerfil()));
        
        frmUsuario.setVisible(true);
        
    }//GEN-LAST:event_jtListaUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmListaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btListar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtListaUsuarios;
    private javax.swing.JTextField tfFiltro;
    // End of variables declaration//GEN-END:variables
}
