/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import crud.UsuarioCRUD;
import database.Database;
import database.DatabaseFactory;
import domain.Usuario;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafael
 */
public class FrmListarUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form FrmListarUsuarios
     */
    private DefaultTableModel modelo;
    private Database db;
    private Connection conn;
    private UsuarioCRUD usuarioCrud;
    
    public FrmListarUsuarios() {
        initComponents();
        modelo = new DefaultTableModel();
        tbListaDeUsuarios.setModel(modelo);
        
        modelo.addColumn("ID");
        modelo.addColumn("USUÁRIO");
        modelo.addColumn("SENHA");
        
        tbListaDeUsuarios.getColumnModel().getColumn(0).setPreferredWidth(5);
        tbListaDeUsuarios.getColumnModel().getColumn(1).setPreferredWidth(10);
        tbListaDeUsuarios.getColumnModel().getColumn(2).setPreferredWidth(30);
        
        db = DatabaseFactory.getDatabase("postgresql");
        conn = db.conectar();
        usuarioCrud = new UsuarioCRUD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanesUsuarios = new javax.swing.JScrollPane();
        tbListaDeUsuarios = new javax.swing.JTable();
        btListarUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbListaDeUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPanesUsuarios.setViewportView(tbListaDeUsuarios);

        btListarUsuarios.setText("Listar Usuários");
        btListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(scrollPanesUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btListarUsuarios)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btListarUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(scrollPanesUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarUsuariosActionPerformed
        // TODO add your handling code here:
        ArrayList<Usuario> lista;
        if(modelo.getRowCount() > 0){
            for(int i=modelo.getRowCount() -1; i >= 0; i--){
                modelo.removeRow(i);
            }
        }
        lista = usuarioCrud.ler(this.conn);
        for(Usuario u: lista){
            modelo.addRow(new Object[]{u.getId(), u.getUsuario(), u.getSenha()});
        }
    }//GEN-LAST:event_btListarUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmListarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btListarUsuarios;
    private javax.swing.JScrollPane scrollPanesUsuarios;
    private javax.swing.JTable tbListaDeUsuarios;
    // End of variables declaration//GEN-END:variables
}
